import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Script from "next/script";
import "./prismjs/prism.css";

export const metadata: Metadata = {
  title: "Next.js Markdown Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="main-container">
          <header>
            <div className="logo">
              <Link href="/">Backbencher.dev</Link> by Joby Joseph
            </div>
          </header>
          <div>{children}</div>
        </div>
        <Script src="./prismjs/prism.js" />
      </body>
    </html>
  );
}
